/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppBoardRouteImport } from './routes/_app/board'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppClientsRouteImport } from './routes/_app/clients'
import { Route as AppFilesRouteImport } from './routes/_app/files'
import { Route as AppMinutesRouteImport } from './routes/_app/minutes'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppVaultRouteImport } from './routes/_app/vault'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiOtpSinkRouteImport } from './routes/api/otp-sink'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'
import { Route as ApiInternalAlertsRouteImport } from './routes/api/internal/alerts'
import { Route as ApiCalendarGoogleCallbackRouteImport } from './routes/api/calendar/google/callback'
import { Route as ApiCalendarMicrosoftCallbackRouteImport } from './routes/api/calendar/microsoft/callback'
import { Route as ApiCalendarOutlookCallbackRouteImport } from './routes/api/calendar/outlook/callback'
import { Route as ApiFilesUploadsIdRouteImport } from './routes/api/files/uploads/$id'
import { Route as ApiMediaUploadsIdRouteImport } from './routes/api/media/uploads/$id'
import { Route as ApiVaultAssetsIdRouteImport } from './routes/api/vault/assets/$id'
import { Route as ApiVaultUploadsIdRouteImport } from './routes/api/vault/uploads/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBoardRoute = AppBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppClientsRoute = AppClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppMinutesRoute = AppMinutesRouteImport.update({
  id: '/minutes',
  path: '/minutes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtpSinkRoute = ApiOtpSinkRouteImport.update({
  id: '/api/otp-sink',
  path: '/api/otp-sink',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalAlertsRoute = ApiInternalAlertsRouteImport.update({
  id: '/api/internal/alerts',
  path: '/api/internal/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarGoogleCallbackRoute =
  ApiCalendarGoogleCallbackRouteImport.update({
    id: '/api/calendar/google/callback',
    path: '/api/calendar/google/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalendarMicrosoftCallbackRoute =
  ApiCalendarMicrosoftCallbackRouteImport.update({
    id: '/api/calendar/microsoft/callback',
    path: '/api/calendar/microsoft/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCalendarOutlookCallbackRoute =
  ApiCalendarOutlookCallbackRouteImport.update({
    id: '/api/calendar/outlook/callback',
    path: '/api/calendar/outlook/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFilesUploadsIdRoute = ApiFilesUploadsIdRouteImport.update({
  id: '/api/files/uploads/$id',
  path: '/api/files/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaUploadsIdRoute = ApiMediaUploadsIdRouteImport.update({
  id: '/api/media/uploads/$id',
  path: '/api/media/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultAssetsIdRoute = ApiVaultAssetsIdRouteImport.update({
  id: '/api/vault/assets/$id',
  path: '/api/vault/assets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVaultUploadsIdRoute = ApiVaultUploadsIdRouteImport.update({
  id: '/api/vault/uploads/$id',
  path: '/api/vault/uploads/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/clients': typeof AppClientsRoute
  '/files': typeof AppFilesRoute
  '/minutes': typeof AppMinutesRoute
  '/notes': typeof AppNotesRoute
  '/settings': typeof AppSettingsRoute
  '/vault': typeof AppVaultRoute
  '/api/health': typeof ApiHealthRoute
  '/api/otp-sink': typeof ApiOtpSinkRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/internal/alerts': typeof ApiInternalAlertsRoute
  '/api/calendar/google/callback': typeof ApiCalendarGoogleCallbackRoute
  '/api/calendar/microsoft/callback': typeof ApiCalendarMicrosoftCallbackRoute
  '/api/calendar/outlook/callback': typeof ApiCalendarOutlookCallbackRoute
  '/api/files/uploads/$id': typeof ApiFilesUploadsIdRoute
  '/api/media/uploads/$id': typeof ApiMediaUploadsIdRoute
  '/api/vault/assets/$id': typeof ApiVaultAssetsIdRoute
  '/api/vault/uploads/$id': typeof ApiVaultUploadsIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/board': typeof AppBoardRoute
  '/calendar': typeof AppCalendarRoute
  '/chat': typeof AppChatRoute
  '/clients': typeof AppClientsRoute
  '/files': typeof AppFilesRoute
  '/minutes': typeof AppMinutesRoute
  '/notes': typeof AppNotesRoute
  '/settings': typeof AppSettingsRoute
  '/vault': typeof AppVaultRoute
  '/api/health': typeof ApiHealthRoute
  '/api/otp-sink': typeof ApiOtpSinkRoute
  '/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/internal/alerts': typeof ApiInternalAlertsRoute
  '/api/calendar/google/callback': typeof ApiCalendarGoogleCallbackRoute
  '/api/calendar/microsoft/callback': typeof ApiCalendarMicrosoftCallbackRoute
  '/api/calendar/outlook/callback': typeof ApiCalendarOutlookCallbackRoute
  '/api/files/uploads/$id': typeof ApiFilesUploadsIdRoute
  '/api/media/uploads/$id': typeof ApiMediaUploadsIdRoute
  '/api/vault/assets/$id': typeof ApiVaultAssetsIdRoute
  '/api/vault/uploads/$id': typeof ApiVaultUploadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/board': typeof AppBoardRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/clients': typeof AppClientsRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/minutes': typeof AppMinutesRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/vault': typeof AppVaultRoute
  '/api/health': typeof ApiHealthRoute
  '/api/otp-sink': typeof ApiOtpSinkRoute
  '/_app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/internal/alerts': typeof ApiInternalAlertsRoute
  '/api/calendar/google/callback': typeof ApiCalendarGoogleCallbackRoute
  '/api/calendar/microsoft/callback': typeof ApiCalendarMicrosoftCallbackRoute
  '/api/calendar/outlook/callback': typeof ApiCalendarOutlookCallbackRoute
  '/api/files/uploads/$id': typeof ApiFilesUploadsIdRoute
  '/api/media/uploads/$id': typeof ApiMediaUploadsIdRoute
  '/api/vault/assets/$id': typeof ApiVaultAssetsIdRoute
  '/api/vault/uploads/$id': typeof ApiVaultUploadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/board'
    | '/calendar'
    | '/chat'
    | '/clients'
    | '/files'
    | '/minutes'
    | '/notes'
    | '/settings'
    | '/vault'
    | '/api/health'
    | '/api/otp-sink'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/internal/alerts'
    | '/api/calendar/google/callback'
    | '/api/calendar/microsoft/callback'
    | '/api/calendar/outlook/callback'
    | '/api/files/uploads/$id'
    | '/api/media/uploads/$id'
    | '/api/vault/assets/$id'
    | '/api/vault/uploads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/board'
    | '/calendar'
    | '/chat'
    | '/clients'
    | '/files'
    | '/minutes'
    | '/notes'
    | '/settings'
    | '/vault'
    | '/api/health'
    | '/api/otp-sink'
    | '/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/internal/alerts'
    | '/api/calendar/google/callback'
    | '/api/calendar/microsoft/callback'
    | '/api/calendar/outlook/callback'
    | '/api/files/uploads/$id'
    | '/api/media/uploads/$id'
    | '/api/vault/assets/$id'
    | '/api/vault/uploads/$id'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/board'
    | '/_app/calendar'
    | '/_app/chat'
    | '/_app/clients'
    | '/_app/files'
    | '/_app/minutes'
    | '/_app/notes'
    | '/_app/settings'
    | '/_app/vault'
    | '/api/health'
    | '/api/otp-sink'
    | '/_app/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/internal/alerts'
    | '/api/calendar/google/callback'
    | '/api/calendar/microsoft/callback'
    | '/api/calendar/outlook/callback'
    | '/api/files/uploads/$id'
    | '/api/media/uploads/$id'
    | '/api/vault/assets/$id'
    | '/api/vault/uploads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOtpSinkRoute: typeof ApiOtpSinkRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
  ApiInternalAlertsRoute: typeof ApiInternalAlertsRoute
  ApiCalendarGoogleCallbackRoute: typeof ApiCalendarGoogleCallbackRoute
  ApiCalendarMicrosoftCallbackRoute: typeof ApiCalendarMicrosoftCallbackRoute
  ApiCalendarOutlookCallbackRoute: typeof ApiCalendarOutlookCallbackRoute
  ApiFilesUploadsIdRoute: typeof ApiFilesUploadsIdRoute
  ApiMediaUploadsIdRoute: typeof ApiMediaUploadsIdRoute
  ApiVaultAssetsIdRoute: typeof ApiVaultAssetsIdRoute
  ApiVaultUploadsIdRoute: typeof ApiVaultUploadsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/board': {
      id: '/_app/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AppBoardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clients': {
      id: '/_app/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AppClientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/minutes': {
      id: '/_app/minutes'
      path: '/minutes'
      fullPath: '/minutes'
      preLoaderRoute: typeof AppMinutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otp-sink': {
      id: '/api/otp-sink'
      path: '/api/otp-sink'
      fullPath: '/api/otp-sink'
      preLoaderRoute: typeof ApiOtpSinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/alerts': {
      id: '/api/internal/alerts'
      path: '/api/internal/alerts'
      fullPath: '/api/internal/alerts'
      preLoaderRoute: typeof ApiInternalAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/google/callback': {
      id: '/api/calendar/google/callback'
      path: '/api/calendar/google/callback'
      fullPath: '/api/calendar/google/callback'
      preLoaderRoute: typeof ApiCalendarGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/microsoft/callback': {
      id: '/api/calendar/microsoft/callback'
      path: '/api/calendar/microsoft/callback'
      fullPath: '/api/calendar/microsoft/callback'
      preLoaderRoute: typeof ApiCalendarMicrosoftCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/outlook/callback': {
      id: '/api/calendar/outlook/callback'
      path: '/api/calendar/outlook/callback'
      fullPath: '/api/calendar/outlook/callback'
      preLoaderRoute: typeof ApiCalendarOutlookCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/uploads/$id': {
      id: '/api/files/uploads/$id'
      path: '/api/files/uploads/$id'
      fullPath: '/api/files/uploads/$id'
      preLoaderRoute: typeof ApiFilesUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/uploads/$id': {
      id: '/api/media/uploads/$id'
      path: '/api/media/uploads/$id'
      fullPath: '/api/media/uploads/$id'
      preLoaderRoute: typeof ApiMediaUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/assets/$id': {
      id: '/api/vault/assets/$id'
      path: '/api/vault/assets/$id'
      fullPath: '/api/vault/assets/$id'
      preLoaderRoute: typeof ApiVaultAssetsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vault/uploads/$id': {
      id: '/api/vault/uploads/$id'
      path: '/api/vault/uploads/$id'
      fullPath: '/api/vault/uploads/$id'
      preLoaderRoute: typeof ApiVaultUploadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBoardRoute: typeof AppBoardRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppChatRoute: typeof AppChatRoute
  AppClientsRoute: typeof AppClientsRoute
  AppFilesRoute: typeof AppFilesRoute
  AppMinutesRoute: typeof AppMinutesRoute
  AppNotesRoute: typeof AppNotesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBoardRoute: AppBoardRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppChatRoute: AppChatRoute,
  AppClientsRoute: AppClientsRoute,
  AppFilesRoute: AppFilesRoute,
  AppMinutesRoute: AppMinutesRoute,
  AppNotesRoute: AppNotesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOtpSinkRoute: ApiOtpSinkRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
  ApiInternalAlertsRoute: ApiInternalAlertsRoute,
  ApiCalendarGoogleCallbackRoute: ApiCalendarGoogleCallbackRoute,
  ApiCalendarMicrosoftCallbackRoute: ApiCalendarMicrosoftCallbackRoute,
  ApiCalendarOutlookCallbackRoute: ApiCalendarOutlookCallbackRoute,
  ApiFilesUploadsIdRoute: ApiFilesUploadsIdRoute,
  ApiMediaUploadsIdRoute: ApiMediaUploadsIdRoute,
  ApiVaultAssetsIdRoute: ApiVaultAssetsIdRoute,
  ApiVaultUploadsIdRoute: ApiVaultUploadsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
